CREATE TYPE "public"."status" AS ENUM('pending', 'in-progress', 'completed');--> statement-breakpoint
CREATE TABLE "t3-app_task" (
	"id" uuid PRIMARY KEY DEFAULT gen_random_uuid() NOT NULL,
	"title" varchar(256) NOT NULL,
	"description" text,
	"status" "status" DEFAULT 'pending' NOT NULL,
	"imageUrl" text,
	"createdAt" timestamp with time zone DEFAULT CURRENT_TIMESTAMP NOT NULL
);
--> statement-breakpoint
CREATE TABLE "t3-app_post" (
	"id" integer PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY (sequence name "t3-app_post_id_seq" INCREMENT BY 1 MINVALUE 1 MAXVALUE 2147483647 START WITH 1 CACHE 1),
	"name" varchar(256),
	"createdAt" timestamp with time zone DEFAULT CURRENT_TIMESTAMP NOT NULL,
	"updatedAt" timestamp with time zone
);
--> statement-breakpoint
CREATE INDEX "title_idx" ON "t3-app_task" USING btree ("title");--> statement-breakpoint
CREATE INDEX "name_idx" ON "t3-app_post" USING btree ("name");